// Cambridge Shades - CBSE Grade 2 - Complete Chapter Data
// Upgraded from Grade 1 for next academic year

export const subjects = [
    {
        id: 'english',
        name: 'English',
        icon: '📖',
        color: '#E91E63',
        gradient: 'linear-gradient(135deg, #E91E63, #F06292)',
        description: 'Stories, poems, grammar & creative writing',
        chapters: [
            {
                id: 'eng-ch1',
                name: 'The Giving Tree',
                type: 'story',
                topics: ['reading comprehension', 'vocabulary', 'story questions', 'new words', 'word meanings', 'paragraph writing'],
            },
            {
                id: 'eng-poem1',
                name: 'The Wind and the Sun',
                type: 'poem',
                topics: ['rhyming words', 'vocabulary', 'poem appreciation', 'word meanings', 'adjectives', 'similes'],
            },
            {
                id: 'eng-ch2',
                name: 'The Clever Fox',
                type: 'story',
                topics: ['reading comprehension', 'vocabulary', 'sentence formation', 'new words', 'antonyms', 'synonyms'],
            },
            {
                id: 'eng-poem2',
                name: 'Rain on the Rooftop',
                type: 'poem',
                topics: ['rhyming words', 'describing words', 'poem appreciation', 'word meanings', 'adjectives'],
            },
            {
                id: 'eng-ch3',
                name: 'The Monkey and the Crocodile',
                type: 'story',
                topics: ['reading comprehension', 'vocabulary', 'moral of the story', 'character traits', 'paragraph writing', 'dialogue'],
            },
            {
                id: 'eng-poem3',
                name: 'Boats Sail on the Rivers',
                type: 'poem',
                topics: ['rhyming words', 'nature words', 'poem comprehension', 'metaphors', 'creative writing'],
            },
            {
                id: 'eng-ch4',
                name: 'The Enormous Turnip',
                type: 'story',
                topics: ['reading comprehension', 'vocabulary', 'teamwork', 'sequencing events', 'sentence rewriting', 'past tense'],
            },
            {
                id: 'eng-poem4',
                name: 'If I Were a Butterfly',
                type: 'poem',
                topics: ['imagination', 'describing words', 'rhyming words', 'creative writing', 'poem comprehension'],
            },
            {
                id: 'eng-ch5',
                name: 'The Thirsty Crow',
                type: 'story',
                topics: ['reading comprehension', 'problem solving', 'vocabulary', 'moral values', 'sentence formation', 'tenses'],
            },
            {
                id: 'eng-grammar',
                name: 'Grammar & Writing Skills',
                type: 'revision',
                topics: ['nouns', 'pronouns', 'verbs', 'adjectives', 'articles', 'prepositions', 'tenses', 'singular-plural', 'punctuation', 'paragraph writing', 'letter writing', 'picture composition'],
            },
        ],
    },
    {
        id: 'maths',
        name: 'Mathematics',
        icon: '🔢',
        color: '#2196F3',
        gradient: 'linear-gradient(135deg, #2196F3, #64B5F6)',
        description: 'Numbers, operations, shapes & problem solving',
        chapters: [
            {
                id: 'math-ch1',
                name: 'Numbers up to 1000',
                type: 'chapter',
                topics: ['number names', 'counting', 'before-after-between', 'ascending-descending order', 'place value hundreds-tens-ones', 'expanded form', 'comparing numbers', 'skip counting'],
            },
            {
                id: 'math-ch2',
                name: 'Addition and Subtraction (3-digit)',
                type: 'chapter',
                topics: ['addition without carry', 'addition with carry', 'subtraction without borrow', 'subtraction with borrow', 'word problems', 'number sentences', 'estimation'],
            },
            {
                id: 'math-ch3',
                name: 'Multiplication Tables (2 to 10)',
                type: 'chapter',
                topics: ['multiplication tables 2-10', 'multiplication as repeated addition', 'multiplication as groups', 'word problems', 'skip counting', 'properties of multiplication'],
            },
            {
                id: 'math-ch4',
                name: 'Division',
                type: 'chapter',
                topics: ['division as equal sharing', 'division as grouping', 'division facts', 'division word problems', 'relation between multiplication and division'],
            },
            {
                id: 'math-ch5',
                name: 'Fractions',
                type: 'chapter',
                topics: ['half', 'one-fourth', 'three-fourths', 'fraction of a whole', 'fraction of a collection', 'comparing fractions', 'shading fractions'],
            },
            {
                id: 'math-ch6',
                name: 'Measurement (Length, Weight, Capacity)',
                type: 'chapter',
                topics: ['metres and centimetres', 'kilograms and grams', 'litres and millilitres', 'measuring length', 'comparing weights', 'word problems with measurement'],
            },
            {
                id: 'math-ch7',
                name: 'Time',
                type: 'chapter',
                topics: ['reading clock', 'hours and minutes', 'quarter past', 'quarter to', 'half past', 'days of the week', 'months of the year', 'calendar reading', 'AM and PM'],
            },
            {
                id: 'math-ch8',
                name: 'Money',
                type: 'chapter',
                topics: ['coins and notes', 'rupees and paise', 'adding money', 'subtracting money', 'making change', 'word problems with money', 'bill reading'],
            },
            {
                id: 'math-ch9',
                name: 'Shapes and Patterns',
                type: 'chapter',
                topics: ['2D shapes', '3D shapes', 'lines of symmetry', 'patterns', 'tessellations', 'shape properties', 'sides and corners'],
            },
            {
                id: 'math-ch10',
                name: 'Data Handling',
                type: 'chapter',
                topics: ['tally marks', 'pictograph', 'bar graph basics', 'data collection', 'reading data', 'interpreting graphs'],
            },
            {
                id: 'math-mental',
                name: 'Mental Maths & Revision',
                type: 'revision',
                topics: ['quick addition', 'quick subtraction', 'multiplication facts', 'number patterns', 'skip counting', 'place value', 'word problems', 'estimation'],
            },
        ],
    },
    {
        id: 'evs',
        name: 'Environmental Studies',
        icon: '🌍',
        color: '#4CAF50',
        gradient: 'linear-gradient(135deg, #4CAF50, #81C784)',
        description: 'Nature, science, society & daily life',
        chapters: [
            {
                id: 'evs-ch1',
                name: 'Plants Around Us',
                type: 'chapter',
                topics: ['parts of a plant', 'types of plants', 'plant life cycle', 'seed germination', 'uses of plants', 'caring for plants'],
            },
            {
                id: 'evs-ch2',
                name: 'Animals and Their Habitats',
                type: 'chapter',
                topics: ['pet animals', 'wild animals', 'farm animals', 'water animals', 'animal habitats', 'food chain basics', 'animal adaptations'],
            },
            {
                id: 'evs-ch3',
                name: 'Our Body',
                type: 'chapter',
                topics: ['body parts', 'sense organs', 'bones and muscles', 'healthy habits', 'personal hygiene', 'exercise and rest'],
            },
            {
                id: 'evs-ch4',
                name: 'Food and Nutrition',
                type: 'chapter',
                topics: ['food groups', 'balanced diet', 'vitamins and minerals', 'food from plants', 'food from animals', 'cooking methods', 'food preservation'],
            },
            {
                id: 'evs-ch5',
                name: 'Community Helpers',
                type: 'chapter',
                topics: ['doctor', 'teacher', 'police', 'firefighter', 'farmer', 'postman', 'their tools', 'why they help us'],
            },
            {
                id: 'evs-ch6',
                name: 'Water and Air',
                type: 'chapter',
                topics: ['sources of water', 'water cycle', 'saving water', 'air around us', 'air pollution', 'properties of air', 'clean air'],
            },
            {
                id: 'evs-ch7',
                name: 'Means of Transport',
                type: 'chapter',
                topics: ['land transport', 'water transport', 'air transport', 'public transport', 'traffic rules', 'road safety', 'types of vehicles'],
            },
            {
                id: 'evs-ch8',
                name: 'Festivals of India',
                type: 'chapter',
                topics: ['Diwali', 'Eid', 'Christmas', 'Holi', 'Pongal', 'Onam', 'national festivals', 'unity in diversity'],
            },
            {
                id: 'evs-ch9',
                name: 'Our Earth and Solar System',
                type: 'chapter',
                topics: ['sun', 'moon', 'stars', 'planets', 'day and night', 'seasons', 'rotation and revolution'],
            },
            {
                id: 'evs-ch10',
                name: 'Maps and Directions',
                type: 'chapter',
                topics: ['directions', 'north south east west', 'reading a simple map', 'symbols on map', 'neighbourhood map', 'India on map'],
            },
        ],
    },
    {
        id: 'computer',
        name: 'Computer Science',
        icon: '💻',
        color: '#9C27B0',
        gradient: 'linear-gradient(135deg, #9C27B0, #BA68C8)',
        description: 'MS Paint, Notepad & basic computing',
        chapters: [
            {
                id: 'cs-ch1',
                name: 'Parts of a Computer',
                type: 'chapter',
                topics: ['monitor', 'CPU', 'keyboard', 'mouse', 'speaker', 'printer', 'input devices', 'output devices'],
            },
            {
                id: 'cs-ch2',
                name: 'Using a Keyboard',
                type: 'chapter',
                topics: ['alphabet keys', 'number keys', 'special keys', 'shift key', 'caps lock', 'enter key', 'backspace', 'typing practice', 'keyboard shortcuts'],
            },
            {
                id: 'cs-ch3',
                name: 'Fun with MS Paint',
                type: 'chapter',
                topics: ['opening Paint', 'drawing tools', 'pencil tool', 'brush tool', 'shapes', 'fill color', 'eraser', 'saving work', 'text tool'],
            },
            {
                id: 'cs-ch4',
                name: 'Writing with Notepad',
                type: 'chapter',
                topics: ['opening Notepad', 'typing text', 'saving files', 'editing text', 'select all', 'copy paste', 'font size'],
            },
            {
                id: 'cs-ch5',
                name: 'Files and Folders',
                type: 'chapter',
                topics: ['what is a file', 'what is a folder', 'creating folders', 'saving files', 'opening files', 'desktop icons', 'recycle bin'],
            },
        ],
    },
    {
        id: 'hindi',
        name: 'हिंदी (Hindi)',
        icon: '🇮🇳',
        color: '#FF9800',
        gradient: 'linear-gradient(135deg, #FF9800, #FFB74D)',
        description: 'हिंदी भाषा - पढ़ना, लिखना और व्याकरण',
        chapters: [
            {
                id: 'hindi-ch1',
                name: 'संयुक्त अक्षर (Conjunct Consonants)',
                type: 'chapter',
                topics: ['sanyukt akshar', 'ksha', 'tra', 'gya', 'shra', 'conjunct letter words', 'letter writing'],
            },
            {
                id: 'hindi-ch2',
                name: 'बड़ी मात्राएँ (Advanced Matras)',
                type: 'chapter',
                topics: ['ai ki matra', 'au ki matra', 'an ki matra', 'aha ki matra', 'chandrabindu', 'complex matra words'],
            },
            {
                id: 'hindi-ch3',
                name: 'कहानी - चालाक लोमड़ी (Story)',
                type: 'story',
                topics: ['reading comprehension', 'new words', 'questions answers', 'word meanings', 'fill blanks', 'moral of story'],
            },
            {
                id: 'hindi-ch4',
                name: 'कहानी - प्यासा कौआ (Story)',
                type: 'story',
                topics: ['reading comprehension', 'paragraph writing', 'sequencing events', 'character description', 'new words'],
            },
            {
                id: 'hindi-ch5',
                name: 'कविता - तितली रानी (Poems)',
                type: 'poem',
                topics: ['poem recitation', 'rhyming words hindi', 'poem comprehension', 'new words', 'creative writing'],
            },
            {
                id: 'hindi-ch6',
                name: 'कविता - बारिश आई (Poems)',
                type: 'poem',
                topics: ['poem appreciation', 'describing words hindi', 'fill blanks', 'rhyming words', 'nature vocabulary'],
            },
            {
                id: 'hindi-ch7',
                name: 'अनुच्छेद लेखन (Paragraph Writing)',
                type: 'chapter',
                topics: ['paragraph writing', 'essay writing', 'picture composition', 'letter writing', 'my school', 'my family'],
            },
            {
                id: 'hindi-ch8',
                name: 'व्याकरण (Grammar)',
                type: 'revision',
                topics: ['sangya', 'sarvanam', 'kriya', 'visheshan', 'vachan', 'ling', 'vilom shabd', 'paryayvachi', 'sentence formation hindi', 'punctuation'],
            },
        ],
    },
    {
        id: 'telugu',
        name: 'తెలుగు (Telugu)',
        icon: '🏛️',
        color: '#00BCD4',
        gradient: 'linear-gradient(135deg, #00BCD4, #4DD0E1)',
        description: 'తెలుగు భాష - చదవడం, రాయడం మరియు వ్యాకరణం',
        chapters: [
            {
                id: 'tel-ch1',
                name: 'ఒత్తులు (Otthulu - Conjuncts)',
                type: 'chapter',
                topics: ['otthulu', 'conjunct consonants telugu', 'letter combinations', 'reading practice', 'writing practice'],
            },
            {
                id: 'tel-ch2',
                name: 'వత్తు పదాలు (Conjunct Words)',
                type: 'chapter',
                topics: ['vattu words', 'complex words', 'sentence formation', 'reading fluency', 'dictation words'],
            },
            {
                id: 'tel-ch3',
                name: 'కథ - తెలివైన కుందేలు (Story)',
                type: 'story',
                topics: ['reading comprehension telugu', 'new words telugu', 'questions answers telugu', 'word meanings telugu', 'moral of story'],
            },
            {
                id: 'tel-ch4',
                name: 'కథ - నక్క మరియు ద్రాక్ష (Story)',
                type: 'story',
                topics: ['reading comprehension', 'vocabulary', 'paragraph writing telugu', 'sequencing', 'character traits'],
            },
            {
                id: 'tel-ch5',
                name: 'పద్యం - చిట్టి చిలకమ్మ (Poem)',
                type: 'poem',
                topics: ['poem recitation telugu', 'rhyming words telugu', 'poem comprehension telugu', 'new words'],
            },
            {
                id: 'tel-ch6',
                name: 'అనుచ్ఛేదం (Paragraph Writing)',
                type: 'chapter',
                topics: ['paragraph writing telugu', 'essay writing telugu', 'picture composition', 'letter writing telugu'],
            },
            {
                id: 'tel-ch7',
                name: 'వ్యాకరణం (Grammar)',
                type: 'revision',
                topics: ['naamavachakam', 'kriyavachakam', 'viseshanam', 'singular plural telugu', 'opposites telugu', 'sentence formation telugu', 'punctuation telugu'],
            },
        ],
    },
    {
        id: 'values',
        name: 'Value Education',
        icon: '🌟',
        color: '#795548',
        gradient: 'linear-gradient(135deg, #795548, #A1887F)',
        description: 'Values, responsibility & good citizenship',
        chapters: [
            {
                id: 'val-ch1',
                name: 'Responsibility',
                type: 'chapter',
                topics: ['being responsible', 'taking care of things', 'completing tasks', 'homework habits', 'helping at home'],
            },
            {
                id: 'val-ch2',
                name: 'Honesty and Truthfulness',
                type: 'chapter',
                topics: ['telling the truth', 'being honest', 'trust', 'consequences of lying', 'courage to be honest'],
            },
            {
                id: 'val-ch3',
                name: 'Caring for the Environment',
                type: 'chapter',
                topics: ['save trees', 'reduce waste', 'recycle', 'clean surroundings', 'love for nature', 'pollution'],
            },
            {
                id: 'val-ch4',
                name: 'Respecting Diversity',
                type: 'chapter',
                topics: ['different cultures', 'different languages', 'different foods', 'respecting differences', 'unity in diversity', 'being inclusive'],
            },
            {
                id: 'val-ch5',
                name: 'Being a Good Citizen',
                type: 'chapter',
                topics: ['following rules', 'respecting elders', 'helping community', 'public property', 'national symbols', 'national pride'],
            },
            {
                id: 'val-ch6',
                name: 'Empathy and Compassion',
                type: 'chapter',
                topics: ['understanding feelings', 'being kind', 'helping those in need', 'sharing', 'caring for animals', 'forgiveness'],
            },
        ],
    },
    {
        id: 'painting',
        name: 'Painting & Art',
        icon: '🎨',
        color: '#E65100',
        gradient: 'linear-gradient(135deg, #E65100, #FF8F00, #FFB300)',
        description: '🚂 Train-themed creative art & learning',
        chapters: [
            {
                id: 'art-ch1',
                name: '🚉 Train Station Scene',
                type: 'painting',
                topics: ['draw a train station', 'people at station', 'ticket counter', 'platform', 'labeling parts', 'community places', 'colors and shading'],
            },
            {
                id: 'art-ch2',
                name: '🚂 Parts of a Train',
                type: 'painting',
                topics: ['engine', 'carriages', 'wheels', 'tracks', 'chimney', 'windows', 'labeling parts', 'how machines work'],
            },
            {
                id: 'art-ch3',
                name: '🌄 Train Journey Through India',
                type: 'painting',
                topics: ['Indian landmarks', 'mountains', 'rivers', 'cities', 'drawing landscapes', 'geography through art', 'map drawing'],
            },
            {
                id: 'art-ch4',
                name: '🔢 Train & Math Fun',
                type: 'painting',
                topics: ['counting carriages', 'number patterns on trains', 'color by number', 'shape patterns', 'symmetry in trains', 'math through art'],
            },
            {
                id: 'art-ch5',
                name: '🚃 My Dream Train',
                type: 'painting',
                topics: ['creative design', 'imagination', 'dream train features', 'writing about drawing', 'colors and patterns', 'storytelling through art'],
            },
            {
                id: 'art-ch6',
                name: '🌍 Trains Around the World',
                type: 'painting',
                topics: ['bullet train Japan', 'steam train England', 'metro train India', 'TGV France', 'comparing trains', 'general knowledge', 'drawing different trains'],
            },
            {
                id: 'art-ch7',
                name: '🎭 Train Story Comic',
                type: 'painting',
                topics: ['comic strip', 'speech bubbles', 'story sequencing', 'characters on train', 'creative writing', 'drawing expressions'],
            },
            {
                id: 'art-ch8',
                name: '🌈 Train in All Seasons',
                type: 'painting',
                topics: ['summer train', 'rainy train', 'winter train', 'spring train', 'seasons and weather', 'landscape painting', 'colors of seasons'],
            },
        ],
    },
];

export const worksheetTypes = [
    {
        id: 'practice',
        name: 'Practice Worksheet',
        icon: '✏️',
        description: 'Regular practice with mixed question types',
    },
    {
        id: 'revision',
        name: 'Quick Revision',
        icon: '📝',
        description: 'Key concepts summary with short questions',
    },
    {
        id: 'test',
        name: 'Mock Test Paper',
        icon: '📋',
        description: 'Exam-style paper (15 marks) matching school pattern',
    },
    {
        id: 'fun',
        name: 'Fun Activity',
        icon: '🎮',
        description: 'Puzzles, word searches & creative activities',
    },
    {
        id: 'painting',
        name: 'Painting & Art',
        icon: '🎨',
        description: '🚂 Train-themed drawing, coloring & creative art',
    },
];

export const difficultyLevels = [
    { id: 'easy', name: 'Easy', icon: '🌱', description: 'Warming up' },
    { id: 'medium', name: 'Medium', icon: '🌿', description: 'Class level' },
    { id: 'challenge', name: 'Challenge', icon: '🌳', description: 'Exam ready' },
];
