// Cambridge Shades - CBSE Grade 1 - Complete Chapter Data
// Extracted from textbook contents page

export const subjects = [
    {
        id: 'english',
        name: 'English',
        icon: '📖',
        color: '#E91E63',
        gradient: 'linear-gradient(135deg, #E91E63, #F06292)',
        description: 'Stories, poems, grammar & vocabulary',
        chapters: [
            {
                id: 'eng-ch1',
                name: 'The Magic Tree',
                type: 'story',
                topics: ['reading comprehension', 'vocabulary', 'story questions', 'new words', 'word meanings'],
            },
            {
                id: 'eng-poem1',
                name: "A Child's Song",
                type: 'poem',
                topics: ['rhyming words', 'vocabulary', 'poem appreciation', 'word meanings', 'singular-plural'],
            },
            {
                id: 'eng-ch2',
                name: 'The Red Raincoat',
                type: 'story',
                topics: ['reading comprehension', 'vocabulary', 'sentence formation', 'new words', 'opposites'],
            },
            {
                id: 'eng-poem2',
                name: 'The Rainbow',
                type: 'poem',
                topics: ['rhyming words', 'colours', 'poem appreciation', 'word meanings'],
            },
            {
                id: 'eng-ch3',
                name: 'King Lion and Rabbit',
                type: 'story',
                topics: ['reading comprehension', 'vocabulary', 'moral of the story', 'character traits', 'sentence rewriting'],
            },
            {
                id: 'eng-poem3',
                name: 'My Big Fat Cat',
                type: 'poem',
                topics: ['rhyming words', 'describing words', 'poem comprehension', 'adjectives'],
            },
            {
                id: 'eng-ch4',
                name: 'The Poor Woodcutter',
                type: 'story',
                topics: ['reading comprehension', 'vocabulary', 'honesty', 'moral values', 'sentence formation'],
            },
            {
                id: 'eng-poem4',
                name: 'Think, Feel, Act',
                type: 'poem',
                topics: ['feelings', 'actions', 'rhyming words', 'poem comprehension'],
            },
            {
                id: 'eng-revision',
                name: 'Revision & Grammar',
                type: 'revision',
                topics: ['singular-plural', 'rhyming words', 'opposites', 'word meanings', 'sentence formation', 'capital letters', 'full stops', 'naming words', 'action words'],
            },
        ],
    },
    {
        id: 'maths',
        name: 'Mathematics',
        icon: '🔢',
        color: '#2196F3',
        gradient: 'linear-gradient(135deg, #2196F3, #64B5F6)',
        description: 'Numbers, operations & problem solving',
        chapters: [
            {
                id: 'math-ch1',
                name: 'Numbers up to 100',
                type: 'chapter',
                topics: ['number names', 'counting', 'before-after-between', 'ascending-descending order', 'place value', 'expanded form', 'comparing numbers'],
            },
            {
                id: 'math-ch2',
                name: 'Addition and Subtraction up to 99',
                type: 'chapter',
                topics: ['addition without carry', 'addition with carry', 'subtraction without borrow', 'subtraction with borrow', 'word problems', 'number sentences'],
            },
            {
                id: 'math-ch3',
                name: 'Multiplication',
                type: 'chapter',
                topics: ['repeated addition', 'multiplication tables 2-5', 'multiplication as groups', 'word problems', 'skip counting'],
            },
            {
                id: 'math-ch4',
                name: 'Measurement',
                type: 'chapter',
                topics: ['length', 'height', 'weight', 'longer-shorter', 'heavier-lighter', 'taller-shorter', 'comparison'],
            },
            {
                id: 'math-ch5',
                name: 'Money',
                type: 'chapter',
                topics: ['coins', 'notes', 'rupees and paise', 'adding money', 'subtracting money', 'word problems with money'],
            },
            {
                id: 'math-ch6',
                name: 'Data Handling',
                type: 'chapter',
                topics: ['counting objects', 'tally marks', 'pictograph', 'data collection', 'reading data'],
            },
            {
                id: 'math-mental',
                name: 'Mental Maths & Revision',
                type: 'revision',
                topics: ['quick addition', 'quick subtraction', 'number patterns', 'skip counting', 'place value', 'word problems'],
            },
        ],
    },
    {
        id: 'evs',
        name: 'Environmental Studies',
        icon: '🌍',
        color: '#4CAF50',
        gradient: 'linear-gradient(135deg, #4CAF50, #81C784)',
        description: 'Nature, environment & daily life',
        chapters: [
            {
                id: 'evs-ch1',
                name: 'Animals Around Us',
                type: 'chapter',
                topics: ['pet animals', 'wild animals', 'farm animals', 'animal homes', 'animal food', 'animal babies', 'animal sounds'],
            },
            {
                id: 'evs-ch2',
                name: 'Food We Eat',
                type: 'chapter',
                topics: ['healthy food', 'junk food', 'meals of the day', 'food groups', 'fruits and vegetables', 'cooking'],
            },
            {
                id: 'evs-ch3',
                name: 'Houses We Live In',
                type: 'chapter',
                topics: ['types of houses', 'rooms in a house', 'materials used', 'kutcha and pucca houses', 'keeping house clean'],
            },
            {
                id: 'evs-ch4',
                name: 'Clothes We Wear',
                type: 'chapter',
                topics: ['types of clothes', 'clothes for seasons', 'clothes for occasions', 'materials of clothes', 'cotton silk wool'],
            },
            {
                id: 'evs-ch5',
                name: 'Air',
                type: 'chapter',
                topics: ['air around us', 'uses of air', 'air pollution', 'wind', 'things that need air', 'properties of air'],
            },
            {
                id: 'evs-ch6',
                name: 'Water',
                type: 'chapter',
                topics: ['sources of water', 'uses of water', 'saving water', 'clean water', 'water pollution', 'water cycle basics'],
            },
            {
                id: 'evs-ch7',
                name: 'Means of Transport',
                type: 'chapter',
                topics: ['land transport', 'water transport', 'air transport', 'public transport', 'traffic rules', 'safety'],
            },
            {
                id: 'evs-ch8',
                name: 'Communication',
                type: 'chapter',
                topics: ['means of communication', 'telephone', 'letter', 'television', 'radio', 'internet', 'old and new ways'],
            },
            {
                id: 'evs-ch9',
                name: 'The Earth and the Sky',
                type: 'chapter',
                topics: ['sun', 'moon', 'stars', 'day and night', 'seasons', 'solar system basics'],
            },
            {
                id: 'evs-ch10',
                name: 'Weather',
                type: 'chapter',
                topics: ['sunny', 'rainy', 'cloudy', 'windy', 'cold', 'hot', 'seasons and weather', 'clothes and weather'],
            },
        ],
    },
    {
        id: 'computer',
        name: 'Computer Science',
        icon: '💻',
        color: '#9C27B0',
        gradient: 'linear-gradient(135deg, #9C27B0, #BA68C8)',
        description: 'Keyboard, mouse & basic computing',
        chapters: [
            {
                id: 'cs-ch1',
                name: 'Computer Keyboard',
                type: 'chapter',
                topics: ['parts of keyboard', 'alphabet keys', 'number keys', 'space bar', 'enter key', 'backspace key', 'typing practice'],
            },
            {
                id: 'cs-ch2',
                name: 'Fun with Magic Mouse',
                type: 'chapter',
                topics: ['parts of mouse', 'left click', 'right click', 'double click', 'drag and drop', 'mouse pointer'],
            },
            {
                id: 'cs-ch3',
                name: 'Play Time with Tux',
                type: 'chapter',
                topics: ['Tux Paint', 'drawing tools', 'colours', 'stamps', 'shapes', 'saving work', 'fun with computer'],
            },
        ],
    },
    {
        id: 'hindi',
        name: 'हिंदी (Hindi)',
        icon: '🇮🇳',
        color: '#FF9800',
        gradient: 'linear-gradient(135deg, #FF9800, #FFB74D)',
        description: 'हिंदी भाषा - पढ़ना, लिखना और व्याकरण',
        chapters: [
            {
                id: 'hindi-ch1',
                name: 'स्वर और व्यंजन (Vowels & Consonants)',
                type: 'chapter',
                topics: ['swar', 'vyanjan', 'matra', 'letter recognition', 'letter writing', 'aa ki matra', 'ee ki matra'],
            },
            {
                id: 'hindi-ch2',
                name: 'मात्राएँ (Matras)',
                type: 'chapter',
                topics: ['aa ki matra', 'i ki matra', 'ee ki matra', 'u ki matra', 'oo ki matra', 'e ki matra', 'o ki matra', 'matra words'],
            },
            {
                id: 'hindi-ch3',
                name: 'शब्द और वाक्य (Words & Sentences)',
                type: 'chapter',
                topics: ['two letter words', 'three letter words', 'four letter words', 'simple sentences', 'picture reading'],
            },
            {
                id: 'hindi-ch4',
                name: 'कहानी - जादुई पेड़ (Story)',
                type: 'story',
                topics: ['reading comprehension', 'new words', 'questions answers', 'word meanings', 'fill blanks'],
            },
            {
                id: 'hindi-ch5',
                name: 'कविता (Poems)',
                type: 'poem',
                topics: ['poem recitation', 'rhyming words hindi', 'poem comprehension', 'new words'],
            },
            {
                id: 'hindi-ch6',
                name: 'व्याकरण (Grammar)',
                type: 'revision',
                topics: ['naming words hindi', 'action words hindi', 'gender', 'singular plural hindi', 'opposites hindi', 'sentence formation hindi'],
            },
        ],
    },
    {
        id: 'telugu',
        name: 'తెలుగు (Telugu)',
        icon: '🏛️',
        color: '#00BCD4',
        gradient: 'linear-gradient(135deg, #00BCD4, #4DD0E1)',
        description: 'తెలుగు భాష - చదవడం, రాయడం మరియు వ్యాకరణం',
        chapters: [
            {
                id: 'tel-ch1',
                name: 'అచ్చులు - హల్లులు (Vowels & Consonants)',
                type: 'chapter',
                topics: ['achulu', 'hallulu', 'letter recognition telugu', 'letter writing telugu', 'gunintalu'],
            },
            {
                id: 'tel-ch2',
                name: 'గుణింతాలు (Gunintalu)',
                type: 'chapter',
                topics: ['aa gunintam', 'i gunintam', 'ee gunintam', 'u gunintam', 'oo gunintam', 'combining letters'],
            },
            {
                id: 'tel-ch3',
                name: 'పదాలు - వాక్యాలు (Words & Sentences)',
                type: 'chapter',
                topics: ['two letter words telugu', 'three letter words telugu', 'simple sentences telugu', 'picture reading telugu'],
            },
            {
                id: 'tel-ch4',
                name: 'కథ (Story)',
                type: 'story',
                topics: ['reading comprehension telugu', 'new words telugu', 'questions answers telugu', 'word meanings telugu'],
            },
            {
                id: 'tel-ch5',
                name: 'పద్యం (Poem)',
                type: 'poem',
                topics: ['poem recitation telugu', 'rhyming words telugu', 'poem comprehension telugu'],
            },
            {
                id: 'tel-ch6',
                name: 'వ్యాకరణం (Grammar)',
                type: 'revision',
                topics: ['naming words telugu', 'action words telugu', 'singular plural telugu', 'opposites telugu', 'sentence formation telugu'],
            },
        ],
    },
    {
        id: 'values',
        name: 'Value Education',
        icon: '🌟',
        color: '#795548',
        gradient: 'linear-gradient(135deg, #795548, #A1887F)',
        description: 'Values, morals & good citizenship',
        chapters: [
            {
                id: 'val-ch1',
                name: 'Being Friendly',
                type: 'chapter',
                topics: ['friendship', 'sharing', 'helping others', 'being kind to friends', 'playing together'],
            },
            {
                id: 'val-ch2',
                name: 'Being Kind',
                type: 'chapter',
                topics: ['kindness', 'helping elders', 'caring for animals', 'polite words', 'good manners'],
            },
            {
                id: 'val-ch3',
                name: 'Unity is Strength',
                type: 'chapter',
                topics: ['teamwork', 'working together', 'unity', 'cooperation', 'strength in numbers'],
            },
            {
                id: 'val-ch4',
                name: 'Common Good',
                type: 'chapter',
                topics: ['sharing resources', 'community', 'helping neighbors', 'public property', 'cleanliness'],
            },
            {
                id: 'val-ch5',
                name: 'Knowing Your Country',
                type: 'chapter',
                topics: ['India', 'national flag', 'national anthem', 'national symbols', 'festivals', 'states'],
            },
            {
                id: 'val-ch6',
                name: 'Being Non-Violent',
                type: 'chapter',
                topics: ['peace', 'non-violence', 'Mahatma Gandhi', 'conflict resolution', 'gentle words', 'forgiveness'],
            },
        ],
    },
];

export const worksheetTypes = [
    {
        id: 'practice',
        name: 'Practice Worksheet',
        icon: '✏️',
        description: 'Regular practice with mixed question types',
    },
    {
        id: 'revision',
        name: 'Quick Revision',
        icon: '📝',
        description: 'Key concepts summary with short questions',
    },
    {
        id: 'test',
        name: 'Mock Test Paper',
        icon: '📋',
        description: 'Exam-style paper (15 marks) matching school pattern',
    },
    {
        id: 'fun',
        name: 'Fun Activity',
        icon: '🎮',
        description: 'Puzzles, word searches & creative activities',
    },
];

export const difficultyLevels = [
    { id: 'easy', name: 'Easy', icon: '🌱', description: 'Warming up' },
    { id: 'medium', name: 'Medium', icon: '🌿', description: 'Class level' },
    { id: 'challenge', name: 'Challenge', icon: '🌳', description: 'Exam ready' },
];
